# Generated by Django 4.0.3 on 2022-04-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='course',
            field=models.CharField(default='cource 101', max_length=255, null=True),
        ),
    ]
