# Generated by Django 4.0.3 on 2022-04-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_course_pdfview'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfview',
            name='name',
            field=models.CharField(default='course 101', max_length=255, null=True),
        ),
    ]
